query getfood($limit: Int) {
  Article(limit: $limit, filter: { type: { _eq: "food" } }) {
    id
    slug
    type
    video
    press_link
    date_created
    date_created_func {
      day
      month
      year
    }
    translations {
      cover {
        id
      }
      title
    }
    category {
      id
      slug
      translations {
        title
        cover {
          id
        }
      }
      user_created {
        first_name
        last_name
      }
      articles {
        translations {
          content
          title
        }
      }
    }
  }
}
